// <auto-generated />
using System;
using KargoTakip.Altyapi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KargoTakip.Altyapi.Migrations
{
    [DbContext(typeof(UygulamaBaglam))]
    [Migration("20250918063126_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KargoTakip.Alan.Gonderi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CikisAdresi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("KuryeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TakipKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VarisAdresi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TakipKodu")
                        .IsUnique();

                    b.ToTable("Gonderiler");
                });

            modelBuilder.Entity("KargoTakip.Alan.GonderiOlayi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GonderiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Not")
                        .HasColumnType("text");

                    b.Property<int?>("Onceki")
                        .HasColumnType("integer");

                    b.Property<int>("Sonraki")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Zaman")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GonderiOlaylari");
                });

            modelBuilder.Entity("KargoTakip.Alan.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParolaOzu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Eposta = "admin@example.com",
                            ParolaOzu = "$2a$11$j2BxBgufDJFgK8Wvz.zz9uQY7Cp1PYLnvO8YhTeX5LfSxFd2oYMZi",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Eposta = "kurye@example.com",
                            ParolaOzu = "$2a$11$3GAWMtPwt3kMVtM5Cgh1we2N2hvz4yua0Jk3PzUK/hH6Dmum9oBHG",
                            Rol = "Kurye"
                        });
                });

            modelBuilder.Entity("KargoTakip.Alan.Kurye", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plaka")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kuryeler");
                });

            modelBuilder.Entity("KargoTakip.Alan.Musteri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });
#pragma warning restore 612, 618
        }
    }
}
